#ChipScope Core Inserter Project File Version 3.0
#Sat Jan 10 20:09:44 CET 2015
Project.device.designInputFile=D\:\\GitHub\\VHDL\\pandaLight-HDL\\pandaLight-Tests\\HDMI passthrough test\\PANDA_LIGHT_cs.ngc
Project.device.designOutputFile=D\:\\GitHub\\VHDL\\pandaLight-HDL\\pandaLight-Tests\\HDMI passthrough test\\PANDA_LIGHT_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=D\:\\GitHub\\VHDL\\pandaLight-HDL\\pandaLight-Tests\\HDMI passthrough test\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=10
Project.filter<0>=
Project.filter<1>=*P0*
Project.filter<2>=*p0*
Project.filter<3>=*RX_SCL*
Project.filter<4>=*sda*
Project.filter<5>=BIDIR_*
Project.filter<6>=*tx_sda*
Project.filter<7>=*BIDIR_REPEAT_BUFFER_inst/*
Project.filter<8>=*BIDIR_REPEAT_BUFFER*
Project.filter<9>=g_clk
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=g_clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=scl_BIDIR_REPEAT_BUFFER_inst/cur_reg_p0_out
Project.unit<0>.dataChannel<1>=scl_BIDIR_REPEAT_BUFFER_inst/cur_reg_p1_out
Project.unit<0>.dataChannel<2>=sda_BIDIR_REPEAT_BUFFER_inst/cur_reg_p0_out
Project.unit<0>.dataChannel<3>=sda_BIDIR_REPEAT_BUFFER_inst/cur_reg_p1_out
Project.unit<0>.dataDepth=8192
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=4
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=PMOD0_0_OBUF
Project.unit<0>.triggerChannel<0><1>=PMOD0_1_OBUF
Project.unit<0>.triggerChannel<0><2>=PMOD0_2_OBUF
Project.unit<0>.triggerChannel<0><3>=PMOD0_3_OBUF
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=4
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
