#ChipScope Core Inserter Project File Version 3.0
#Sat Sep 17 16:44:50 CEST 2016
Project.device.designInputFile=D\:\\GitHub\\VHDL\\pandaLight-HDL\\pandaLight-Tests\\EDID test\\PANDA_LIGHT_cs.ngc
Project.device.designOutputFile=D\:\\GitHub\\VHDL\\pandaLight-HDL\\pandaLight-Tests\\EDID test\\PANDA_LIGHT_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=D\:\\GitHub\\VHDL\\pandaLight-HDL\\pandaLight-Tests\\EDID test\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=3
Project.filter<0>=
Project.filter<1>=*rx_det*
Project.filter<2>=*rxclk*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=g_clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=rxclk_clk_in
Project.unit<0>.dataChannel<1>=ISERDES2_CLK_MAN_inst/pll_base_locked
Project.unit<0>.dataChannel<2>=rxclk_ioclk_locked
Project.unit<0>.dataChannel<3>=rxclk_serdesstrobe
Project.unit<0>.dataChannel<4>=rx_SIGNAL_SYNC_and_DEBOUNCE_gen[1].rx_det_DEBOUNCE_inst/O
Project.unit<0>.dataDepth=16384
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=5
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=false
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=rxclk_clk_in
Project.unit<0>.triggerChannel<0><1>=ISERDES2_CLK_MAN_inst/pll_base_locked
Project.unit<0>.triggerChannel<0><2>=rxclk_ioclk_locked
Project.unit<0>.triggerChannel<0><3>=rx_SIGNAL_SYNC_and_DEBOUNCE_gen[1].rx_det_DEBOUNCE_inst/O
Project.unit<0>.triggerChannel<0><4>=
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=4
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=0
Project.unit<0>.type=ilapro
